cmake_minimum_required(VERSION 3.24)
project(little_world VERSION 0.5.0 LANGUAGES CXX)
set(sengine_graphics OFF)
add_subdirectory(vendor/sengine EXCLUDE_FROM_ALL)
add_subdirectory(vendor/simulates EXCLUDE_FROM_ALL)
file(GLOB world_sources CONFIGURE_DEPENDS src/simulation/*.cpp src/game/save_library.cpp)
add_library(world ${world_sources})
target_compile_features(world PUBLIC cxx_std_23)
target_include_directories(world PUBLIC src src/simulation src/game)
target_link_libraries(world PUBLIC sengine::sengine simulates::simulates)
